### ISSUE TITLE
Lua error!!!

### ISSUE THREAD

**Issue by letparty** [Blu-x92/simfphys_armed#10]
ERROR!! Ent.Fire delay must be a number!
stack traceback:
        lua/gm13/libs/ent/sv_ent.lua:249: in function 'Fire'
        lua/entities/gmod_sent_vehicle_fphysics_gib.lua:72: in function <lua/entities/gmod_sent_vehicle_fphysics_gib.lua:52>

this happens when the mine explodes the player and it makes the player have fire effect forever unless the player rejoins the game

**Comment by Blu-x92** [comment]
uninstall that gm13 lib it seems to break your game
