### ISSUE TITLE
DIPRIP Vehicles are missing the Class key on the vehicle table.

### ISSUE THREAD

**Issue by wrefgtzweve** [Blu-x92/simfphys_armed#9]
All simfphys and most other mods have a .Class value on the vehicle table, yet the DIPRIP vehicles don't seem to have this.

Example of the hl2 apc:
![image](https://user-images.githubusercontent.com/69946827/179789747-0a978531-b175-4c94-abfb-9536238bed4f.png)

Example of a DIPRIP vehicle:
![image](https://user-images.githubusercontent.com/69946827/179790161-ecaa6cd8-8f7c-44af-bc49-e7049e583c14.png)

https://github.com/Blu-x92/simfphys_armed/blob/de9405b6220470257feab73d27b2c4bea7f187ef/lua/autorun/spawnlist_armedvehicles.lua#L769

**Comment by Blu-x92** [comment]
Class is unused ever since simfphys got its own tab. Nothing wrong here
